Redo the project as a docker-maven-plugin project.
syndesisio/keycloak-openshift pull request #1
Opened 2017-09-25 04:26 UTC by cunningt

Provides property substitution and a pom.xml so we can align the version coming from keycloak-customizations within the pipeline.

2017-09-25 10:19 UTC, zregvart requested changes
perhaps the files root that are copied over to `src/main/docker` can be now removed from the root?

2017-09-25 10:19 UTC, zregvart commented on pom.xml
> +      <id>geeks</id>
💯

2017-09-25 10:19 UTC, zregvart commented on pom.xml
> +    <url>http://github.com/redhat-ipaas/keycloak-customizations/</url>
should this point to `syndesisio/keycloak-openshift` ?

2017-09-25 13:55 UTC, jimmidyson commented on pom.xml
> +  <groupId>com.redhat.ipaas.keycloak</groupId>
`io.syndesis` please. This should be the same top level group ID for all projects in the syndesisio org.

2017-09-26 13:47 UTC, zregvart approved these changes
👍 thanks!

2017-09-26 13:47 UTC, merged